services:
  open-webui:
    container_name: open-webui
    image: ${ACR_REGISTRY}/${ACR_NAMESPACE}/open-webui:${IMAGE_TAG}
    env_file:
      - .env
    volumes:
      - ./:/app/backend/data
    restart: always
    network_mode: host
